Add Activity Post Architecture and Functional Likes Feature
involveMINT/iMPublic pull request #33
Opened 2023-03-23 17:12 UTC by tylowe-labs

**Description:**
This PR adds a substantial amount of content to the repository...
1. Initial architecture for the activity post --> a location in the Change Maker frontend and the backend data objects + orchestration to perform CRUD operations on the activity post
2. Likes Feature --> Adds an MVP implementation of the 'like' feature for an activity post that updates the frontend as well
3. Testing --> Adds *.spec.ts files to test functionality; specifically, NgRx state management and services. We still need to figure out how to test NgRx when `delayWhen(...)` function is used and how to get the *.component.ts test file to compile correctly (issue with imStorageUrl in HTML).

2023-03-23 22:13 UTC, AlexanderChiuy requested changes

2023-03-23 22:13 UTC, AlexanderChiuy commented on libs/client/shell/src/lib/comment/comments/comments.component.html
> +<p>dummy comment page</p>
We should delete this page since we pivoted to the modal

2023-03-24 20:01 UTC, AlexanderChiuy commented on libs/client/shell/src/lib/activityfeed/activitypost/activitypost.component.html
> +        This Proof of Impact has been submitted and is awaiting ServePartner approval or denial.
Going to create a new GitHub issue for this because the structure needs to change entirely to match the Hifi wireframes that the client gave us

2023-03-24 20:01 UTC, AlexanderChiuy commented on libs/client/shared/data-access/src/lib/orchestrations/comment.orchestration.ts
> +    hide!: IClientOrchestration<ICommentOrchestration>['hide'];
We can revisit this later

2023-03-26 15:55 UTC, tylowe-labs commented on libs/client/shell/src/lib/activityfeed/activitypost/activitypost.component.html
I think for this commit let's just completely remove activityfeed/activitypost since it doesn't seem like it is used at all (nothing but dead code)

2023-03-26 21:40 UTC, tylowe-labs commented on libs/client/shared/data-access/src/lib/orchestrations/comment.orchestration.ts
> +    hide!: IClientOrchestration<ICommentOrchestration>['hide'];
@AlexanderChiuy I think this is a good point and we should call them the same thing

2023-03-26 21:45 UTC, tylowe-labs commented on libs/client/shell/src/lib/activityfeed/activitypost/activitypost.component.html
@Bwillia2 @isong2 @Jareltey can one of you plz confirm that you are not using this directory ^^ before we merge PR that removes it? Thanks

2023-03-27 18:26 UTC, merged